motion_correction:  
  gSig_filt  : !!python/tuple [7, 7]
  max_shifts : !!python/tuple [5, 5]
  strides    : !!python/tuple [128, 128]
  overlaps   : !!python/tuple [64, 64]
  splits_rig : 40
  splits_els : 40

  upsample_factor_grid : 4
  max_deviation_rigid  : 3

cnmfe:
  p                   : 1
  K                   : None
  gSig                : 5
  gSiz                : 16
  merge_thresh        : 0.8
  rf                  : 80
  stride              : 40
  tsub                : 2
  ssub                : 2
  Ain                 : None
  low_rank_background : None
  gnb                 : 0
  nb_patch            : 0
  min_corr            : 0.8
  min_pnr             : 12.0
  ssub_B              : 1
  ring_size_factor    : 1.5

component_evaluation:
  decay_time   : 0.4
  min_SNR      : 5
  r_values_min : 0.85
